# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_testmod3')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_testmod3')
    _testmod3 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_testmod3', [dirname(__file__)])
        except ImportError:
            import _testmod3
            return _testmod3
        try:
            _mod = imp.load_module('_testmod3', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _testmod3 = swig_import_helper()
    del swig_import_helper
else:
    import _testmod3
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _testmod3.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _testmod3.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _testmod3.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _testmod3.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _testmod3.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _testmod3.SwigPyIterator_equal(self, x)

    def copy(self):
        return _testmod3.SwigPyIterator_copy(self)

    def next(self):
        return _testmod3.SwigPyIterator_next(self)

    def __next__(self):
        return _testmod3.SwigPyIterator___next__(self)

    def previous(self):
        return _testmod3.SwigPyIterator_previous(self)

    def advance(self, n):
        return _testmod3.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _testmod3.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _testmod3.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _testmod3.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _testmod3.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _testmod3.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _testmod3.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _testmod3.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class map_string_int(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, map_string_int, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, map_string_int, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _testmod3.map_string_int_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _testmod3.map_string_int___nonzero__(self)

    def __bool__(self):
        return _testmod3.map_string_int___bool__(self)

    def __len__(self):
        return _testmod3.map_string_int___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _testmod3.map_string_int___getitem__(self, key)

    def __delitem__(self, key):
        return _testmod3.map_string_int___delitem__(self, key)

    def has_key(self, key):
        return _testmod3.map_string_int_has_key(self, key)

    def keys(self):
        return _testmod3.map_string_int_keys(self)

    def values(self):
        return _testmod3.map_string_int_values(self)

    def items(self):
        return _testmod3.map_string_int_items(self)

    def __contains__(self, key):
        return _testmod3.map_string_int___contains__(self, key)

    def key_iterator(self):
        return _testmod3.map_string_int_key_iterator(self)

    def value_iterator(self):
        return _testmod3.map_string_int_value_iterator(self)

    def __setitem__(self, *args):
        return _testmod3.map_string_int___setitem__(self, *args)

    def asdict(self):
        return _testmod3.map_string_int_asdict(self)

    def __init__(self, *args):
        this = _testmod3.new_map_string_int(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _testmod3.map_string_int_empty(self)

    def size(self):
        return _testmod3.map_string_int_size(self)

    def swap(self, v):
        return _testmod3.map_string_int_swap(self, v)

    def begin(self):
        return _testmod3.map_string_int_begin(self)

    def end(self):
        return _testmod3.map_string_int_end(self)

    def rbegin(self):
        return _testmod3.map_string_int_rbegin(self)

    def rend(self):
        return _testmod3.map_string_int_rend(self)

    def clear(self):
        return _testmod3.map_string_int_clear(self)

    def get_allocator(self):
        return _testmod3.map_string_int_get_allocator(self)

    def count(self, x):
        return _testmod3.map_string_int_count(self, x)

    def erase(self, *args):
        return _testmod3.map_string_int_erase(self, *args)

    def find(self, x):
        return _testmod3.map_string_int_find(self, x)

    def lower_bound(self, x):
        return _testmod3.map_string_int_lower_bound(self, x)

    def upper_bound(self, x):
        return _testmod3.map_string_int_upper_bound(self, x)
    __swig_destroy__ = _testmod3.delete_map_string_int
    __del__ = lambda self: None
map_string_int_swigregister = _testmod3.map_string_int_swigregister
map_string_int_swigregister(map_string_int)

class map_string_double(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, map_string_double, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, map_string_double, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _testmod3.map_string_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _testmod3.map_string_double___nonzero__(self)

    def __bool__(self):
        return _testmod3.map_string_double___bool__(self)

    def __len__(self):
        return _testmod3.map_string_double___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _testmod3.map_string_double___getitem__(self, key)

    def __delitem__(self, key):
        return _testmod3.map_string_double___delitem__(self, key)

    def has_key(self, key):
        return _testmod3.map_string_double_has_key(self, key)

    def keys(self):
        return _testmod3.map_string_double_keys(self)

    def values(self):
        return _testmod3.map_string_double_values(self)

    def items(self):
        return _testmod3.map_string_double_items(self)

    def __contains__(self, key):
        return _testmod3.map_string_double___contains__(self, key)

    def key_iterator(self):
        return _testmod3.map_string_double_key_iterator(self)

    def value_iterator(self):
        return _testmod3.map_string_double_value_iterator(self)

    def __setitem__(self, *args):
        return _testmod3.map_string_double___setitem__(self, *args)

    def asdict(self):
        return _testmod3.map_string_double_asdict(self)

    def __init__(self, *args):
        this = _testmod3.new_map_string_double(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _testmod3.map_string_double_empty(self)

    def size(self):
        return _testmod3.map_string_double_size(self)

    def swap(self, v):
        return _testmod3.map_string_double_swap(self, v)

    def begin(self):
        return _testmod3.map_string_double_begin(self)

    def end(self):
        return _testmod3.map_string_double_end(self)

    def rbegin(self):
        return _testmod3.map_string_double_rbegin(self)

    def rend(self):
        return _testmod3.map_string_double_rend(self)

    def clear(self):
        return _testmod3.map_string_double_clear(self)

    def get_allocator(self):
        return _testmod3.map_string_double_get_allocator(self)

    def count(self, x):
        return _testmod3.map_string_double_count(self, x)

    def erase(self, *args):
        return _testmod3.map_string_double_erase(self, *args)

    def find(self, x):
        return _testmod3.map_string_double_find(self, x)

    def lower_bound(self, x):
        return _testmod3.map_string_double_lower_bound(self, x)

    def upper_bound(self, x):
        return _testmod3.map_string_double_upper_bound(self, x)
    __swig_destroy__ = _testmod3.delete_map_string_double
    __del__ = lambda self: None
map_string_double_swigregister = _testmod3.map_string_double_swigregister
map_string_double_swigregister(map_string_double)

class map_string_string(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, map_string_string, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, map_string_string, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _testmod3.map_string_string_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _testmod3.map_string_string___nonzero__(self)

    def __bool__(self):
        return _testmod3.map_string_string___bool__(self)

    def __len__(self):
        return _testmod3.map_string_string___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _testmod3.map_string_string___getitem__(self, key)

    def __delitem__(self, key):
        return _testmod3.map_string_string___delitem__(self, key)

    def has_key(self, key):
        return _testmod3.map_string_string_has_key(self, key)

    def keys(self):
        return _testmod3.map_string_string_keys(self)

    def values(self):
        return _testmod3.map_string_string_values(self)

    def items(self):
        return _testmod3.map_string_string_items(self)

    def __contains__(self, key):
        return _testmod3.map_string_string___contains__(self, key)

    def key_iterator(self):
        return _testmod3.map_string_string_key_iterator(self)

    def value_iterator(self):
        return _testmod3.map_string_string_value_iterator(self)

    def __setitem__(self, *args):
        return _testmod3.map_string_string___setitem__(self, *args)

    def asdict(self):
        return _testmod3.map_string_string_asdict(self)

    def __init__(self, *args):
        this = _testmod3.new_map_string_string(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _testmod3.map_string_string_empty(self)

    def size(self):
        return _testmod3.map_string_string_size(self)

    def swap(self, v):
        return _testmod3.map_string_string_swap(self, v)

    def begin(self):
        return _testmod3.map_string_string_begin(self)

    def end(self):
        return _testmod3.map_string_string_end(self)

    def rbegin(self):
        return _testmod3.map_string_string_rbegin(self)

    def rend(self):
        return _testmod3.map_string_string_rend(self)

    def clear(self):
        return _testmod3.map_string_string_clear(self)

    def get_allocator(self):
        return _testmod3.map_string_string_get_allocator(self)

    def count(self, x):
        return _testmod3.map_string_string_count(self, x)

    def erase(self, *args):
        return _testmod3.map_string_string_erase(self, *args)

    def find(self, x):
        return _testmod3.map_string_string_find(self, x)

    def lower_bound(self, x):
        return _testmod3.map_string_string_lower_bound(self, x)

    def upper_bound(self, x):
        return _testmod3.map_string_string_upper_bound(self, x)
    __swig_destroy__ = _testmod3.delete_map_string_string
    __del__ = lambda self: None
map_string_string_swigregister = _testmod3.map_string_string_swigregister
map_string_string_swigregister(map_string_string)

class Myclass(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Myclass, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Myclass, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _testmod3.new_Myclass(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def testArma(self, arg2):
        return _testmod3.Myclass_testArma(self, arg2)

    def getEmptyArma(self, n):
        return _testmod3.Myclass_getEmptyArma(self, n)
    __swig_setmethods__["myMat"] = _testmod3.Myclass_myMat_set
    __swig_getmethods__["myMat"] = _testmod3.Myclass_myMat_get
    if _newclass:
        myMat = _swig_property(_testmod3.Myclass_myMat_get, _testmod3.Myclass_myMat_set)
    __swig_destroy__ = _testmod3.delete_Myclass
    __del__ = lambda self: None
Myclass_swigregister = _testmod3.Myclass_swigregister
Myclass_swigregister(Myclass)

# This file is compatible with both classic and new-style classes.


