#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: $0 path"
  exit
fi


path=$1
mkdir $path

tmux capture-pane -e -J

echo "Files will be saved in $path"

echo 'Generated by tmux_capture.sh' > $path/typescript
tmux show-buffer >> $path/typescript

tmux display -p '#{pane_height} #{pane_width}' > $path/dims

